[#45] Fix errors in initialize_pusher (#46)
* [#45] Fix typo: Apparently should be `pusher`, not `push`

Prevents error:

  wrong number of arguments (given 0, expected 1..2)

* [#45] Handle the case where pusher is nil

Prevents error:

  undefined method `to_sym' for nil:NilClass

* Make pushing enabled by default

Make the default value true for global_settings_allow_push?, global_category_settings_allow_push?,
and local_category_settings_allow_push?.

Similar to how we made settings_allow_create? true by default in #37.

* Fix RuboCop offense:

  Metrics/PerceivedComplexity: Perceived complexity for can_push? is too high. [8/7]

* Simplify some logic

* Rename the settings key for enabling/disabling pushing from :index to :pusher_enabled

... to make it more self-explanatory.