Fix error when calling Subscriber#subscribe:
  NoMethodError:
    undefined method `create!' for nil:NilClass

    18: def create_notification_setting
 => 19:   notification_setting.create!
    20: end

Change to use before_create :build_notification_setting, and automatically build
`notification_setting` if object doesn't have one yet like we did in #40.